cinemas:
  singular: "cinema"
  male_age_probabilities:
    3-75: 0.05
    75-80: 0.02
  female_age_probabilities:
    3-75: 0.05
    75-80: 0.02
  neighbours_to_consider: 5
  maximum_distance: 15
  weekend_boost: 1
  drags_household_probability: 0.5
  max_capacity: 1500

# 2019: 176.1 million cinema visitors per year
# (from https://www.cinemauk.org.uk/the-industry/facts-and-figures/uk-cinema-admissions-and-box-office/annual-admissions/)
# age/gender distribution from https://www.statista.com/statistics/296240/age-and-gender-of-the-cinema-audience-uk/

groceries:
  singular: "grocery"
  male_age_probabilities:
    18-65 : 0.90
    65-100 : 0.70
  female_age_probabilities:
    18-65 : 0.90
    65-100 : 0.70
  weekend_boost: 0.70
  drags_household_probability: 0.3
  neighbours_to_consider: 10
  maximum_distance: 10
  max_capacity: 100

gyms:
  singular: "gym"
  male_age_probabilities:
    18-65 : 0.90
    65-100 : 0.60
  female_age_probabilities:
    18-65 : 0.90
    65-100 : 0.60
  neighbours_to_consider: 3
  maximum_distance: 15
  weekend_boost: 0.70
  drags_household_probability: 0.1
  max_capacity: 50

pubs:
  singular: "pub"
  male_age_probabilities:
    18-65 : 0.90
    65-100 : 0.60
  female_age_probabilities:
    18-65 : 0.90
    65-100 : 0.60
  neighbours_to_consider: 15
  maximum_distance: 15
  weekend_boost: 0.70
  drags_household_probability: 0.2
  max_capacity: 100

